### ISSUE TITLE
Testing on 2022.04 will fail

### ISSUE THREAD

**Issue by lizmat** [antononcube/Raku-Text-CodeProcessing#2]
More specifically, in `t/02-string-code-chunks-processing-markdown.t` a test for the compilation error on `$answer ** 2` is expecting:
````
Variable '$answer' is not declared
````
However, that error message was changed in https://github.com/rakudo/rakudo/commit/a56d239d0ce115d60caa772a30acafce933274f0  to:
````
Variable '$answer' is not declared.  Perhaps you forgot a 'sub' if this
was intended to be part of a signature?
````

**Comment by antononcube** [comment]
Thanks! I will update the tests.

**Comment by antononcube** [comment]
I committed a fix to the test, see:

[8e711ed](https://github.com/antononcube/Raku-Text-CodeProcessing/commit/8e711ed4862aeca2fc97b2ab2b72610d5f38e17d)

But I am not sure is that sufficient.

(And probably it is good idea to convert that "is-test" into a "like-test".)

I will update the CPAN package file today or tomorrow.

**Comment by lizmat** [comment]
Making it a "like-test" is probably better, as this change will make your module fail tests on 2022.03 and earlier versions of Rakudo.

**Comment by antononcube** [comment]
Fixed. (Using a universal test. Just verified installation with Raku 2022.04 .) Thanks for bringing this my attention!
