### ISSUE TITLE
Tilde fenced code blocks

### ISSUE THREAD

**Issue by habere-et-dispertire** [antononcube/Raku-Text-CodeProcessing#4]
Hi Anton,

I think both backticks (```) and tildes (~~~) can be delimiters for fenced code blocks ?
It might be good to support both ?
Just a suggestion.
:-)

[Lines 79-80](https://github.com/antononcube/Raku-Text-CodeProcessing/blob/main/lib/Text/CodeProcessing.rakumod)

~~~raku
#| Markdown code chunk ticks
constant $mdTicks = '```';
~~~

**Comment by antononcube** [comment]
Spent ≈ 45 min trying to incorporate the `~~~` block markings without success. Hence, I consider this issue low priority.

Also, I have not seen tildes-marked code blocks used anywhere, except here, and in Markdown and Markdeep documentation. 

See:
- [Markdown](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks)
- [Markdeep](https://casual-effects.com/markdeep/features.md.html#basicformatting/codeblocks)

**Comment by habere-et-dispertire** [comment]
Thank you for trying Anton ! :D

In case it is of any help, here's [another way](https://github.com/retupmoca/p6-markdown/blob/master/lib/Text/Markdown/Document.pm6#L250) I've seen it done.

**Comment by antononcube** [comment]
Implemented -- see the last test 13 of the test file ["02-string-code-chunks-processing-markdown.rakutest"](https://github.com/antononcube/Raku-Text-CodeProcessing/blob/main/t/02-string-code-chunks-processing-markdown.rakutest).

----

The feature should be available in raku.land submitted versions ["Text::CodeProcessing:ver<0.5.6+>"](https://raku.land/zef:antononcube/Text::CodeProcessing).

**Comment by habere-et-dispertire** [comment]
Perfect since I also use four tildes `~~~~` and not three. :]
